/* BenchRoom UI: intentionally dependency-free so the workbench is portable. */
(() => {
  const $ = (id) => document.getElementById(id);
  const state = { csrf: null, endpoints: [], activeEndpointId: null, presets: [], models: [], selectedModels: new Set(), selectedConcurrency: new Set([1, 2, 3, 4]), config: {}, jobs: [], compare: [], currentJob: null, eventSource: null, theme: localStorage.getItem('bench-theme') || 'dark' };
  const defaultConfig = { concurrencies: [1, 2, 3, 4], repetitions: 2, max_tokens: 512, warmup: 1, timeout: 900, temperature: 0, seed: 42, unique_prompts: true, preload: true, prompt: 'Design and explain a production-quality implementation for a moderately complex software component. Include architecture, data structures, concurrency/error handling, edge cases, testing strategy, and representative code. Continue in technical detail until the token budget is exhausted.' };

  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function fmt(value, digits = 2) { return value == null || Number.isNaN(Number(value)) ? '—' : Number(value).toFixed(digits); }
  function fmtTps(value) { return value == null ? '—' : `${fmt(value)} <small>tok/s</small>`; }
  function date(value) { return value ? new Date(Number(value) * 1000).toLocaleString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—'; }
  function toast(message, type = 'info') { const node = document.createElement('div'); node.className = `toast ${type}`; node.textContent = message; $('toast-region').appendChild(node); setTimeout(() => node.remove(), 3800); }
  async function api(path, options = {}) {
    const opts = { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } };
    if (state.csrf && !['GET', 'HEAD'].includes((opts.method || 'GET').toUpperCase())) opts.headers['X-CSRF-Token'] = state.csrf;
    const response = await fetch(path, opts);
    let body = null; try { body = await response.json(); } catch (_) { /* response may be empty */ }
    if (!response.ok) { if (response.status === 401) showAuth(false); throw new Error(body?.error || `HTTP ${response.status}`); }
    return body;
  }

  function showAuth(setup) {
    $('app-shell').classList.add('hidden'); $('auth-shell').classList.remove('hidden');
    $('auth-title').textContent = setup ? '设置 BenchRoom' : '进入 BenchRoom';
    $('auth-copy').textContent = setup ? '首次使用请设置一个局域网管理员密码。' : '局域网访问需要管理员密码。';
    $('auth-submit').textContent = setup ? '保存密码' : '登录';
    $('password-confirm-wrap').classList.toggle('hidden', !setup); $('password-confirm').classList.toggle('hidden', !setup); $('password-input').autocomplete = setup ? 'new-password' : 'current-password';
    $('password-input').focus(); $('auth-shell').dataset.setup = setup ? '1' : '0';
  }
  function showApp() { $('auth-shell').classList.add('hidden'); $('app-shell').classList.remove('hidden'); applyTheme(); }
  function applyTheme() { document.documentElement.dataset.theme = state.theme; }

  async function boot() {
    applyTheme();
    try { const session = await api('/api/session'); if (session.setup_required || !session.authenticated) return showAuth(session.setup_required); state.csrf = session.csrf; showApp(); await loadWorkspace(); } catch (error) { toast(error.message, 'error'); }
  }
  async function loadWorkspace() { await Promise.all([loadEndpoints(), loadPresets(), loadHistory()]); await loadModels(); loadHealth(); }
  async function loadEndpoints() { const body = await api('/api/endpoints'); state.endpoints = body.endpoints || []; state.activeEndpointId = state.activeEndpointId && state.endpoints.some((item) => item.id === state.activeEndpointId) ? state.activeEndpointId : state.endpoints[0]?.id; renderEndpoints(); const selected = state.endpoints.find((item) => item.id === state.activeEndpointId); if (selected) updateEndpointLabel(selected); }
  async function loadPresets() { const body = await api('/api/presets'); state.presets = body.presets || []; renderPresets(); const defaultPreset = state.presets.find((x) => x.is_default) || state.presets[0]; if (defaultPreset && !state.config._initialized) applyPreset(defaultPreset); }
  async function loadModels() { const endpoint = state.endpoints.find((item) => item.id === state.activeEndpointId); if (!endpoint) return; try { const body = await api(`/api/models?endpoint_id=${endpoint.id}`); state.models = body.models || []; renderModels(); if (body.health) setHealth(body.health); } catch (error) { $('model-list').innerHTML = `<div class="empty-block">无法读取模型：${esc(error.message)}</div>`; setHealth(null); } }
  async function loadHealth() { const endpoint = state.endpoints.find((item) => item.id === state.activeEndpointId); if (!endpoint) return; try { const body = await api(`/api/health?endpoint_id=${endpoint.id}`); setHealth(body.health); } catch (_) { setHealth(null); } }
  async function loadHistory() { try { state.jobs = (await api('/api/history')).jobs || []; renderHistory(); renderRecent(); } catch (_) {} }

  function updateEndpointLabel(endpoint) { $('endpoint-select').value = String(endpoint.id); $('active-endpoint-url').textContent = endpoint.base_url.replace('127.0.0.1', 'local').replace('localhost', 'local'); }
  function setHealth(health) { const ok = !!health; [$('top-dot'), $('sidebar-dot')].forEach((dot) => { dot.className = `status-dot ${ok ? 'ok' : 'bad'}`; }); $('top-health').textContent = ok ? `${health.model_loaded ? '模型在线' : '端点在线'}` : '端点不可达'; $('sidebar-health').textContent = ok ? 'inference endpoint online' : 'endpoint offline'; if (health?.system_info) $('system-summary').textContent = JSON.stringify(health.system_info).slice(0, 180); }

  function renderModels() { const box = $('model-list'); if (!state.models.length) { box.innerHTML = '<div class="empty-block">当前端点没有返回模型。点击刷新重试。</div>'; updateSelected(); return; } box.innerHTML = state.models.map((model) => { const selected = state.selectedModels.has(model.id); const loaded = model.loaded; return `<div class="model-option ${selected ? 'selected' : ''}" data-model="${esc(model.id)}"><span class="check-box"></span><input type="checkbox" ${selected ? 'checked' : ''} aria-label="${esc(model.id)}"><label><span class="model-name">${esc(model.id)}</span><span class="model-meta"><span class="model-status ${loaded ? '' : 'off'}">${loaded ? '● loaded' : '○ available'}</span>${esc(model.owned_by || 'OpenAI compatible')}</span></label></div>`; }).join(''); box.querySelectorAll('.model-option').forEach((node) => node.addEventListener('click', () => { const id = node.dataset.model; state.selectedModels.has(id) ? state.selectedModels.delete(id) : state.selectedModels.add(id); renderModels(); updateSelected(); })); updateSelected(); }
  function updateSelected() { const count = state.selectedModels.size; $('model-count').textContent = `${count} selected`; $('selected-summary').textContent = count ? `${count} 个模型 · ${state.selectedConcurrency.size} 个并发档位` : '未选择模型'; $('run-estimate').textContent = count ? `约 ${count * state.selectedConcurrency.size * Number($('repetitions-input').value || 2)} 个批次，模型依次运行` : '选择模型后开始'; $('start-run-btn').disabled = !count || !state.selectedConcurrency.size; }
  function renderPresets() { $('preset-list').innerHTML = state.presets.map((preset) => `<button class="preset-option" data-preset="${preset.id}"><strong>${esc(preset.name)}</strong><small>${esc(preset.description || '')}</small></button>`).join(''); $('preset-list').querySelectorAll('.preset-option').forEach((node) => node.addEventListener('click', () => { const preset = state.presets.find((item) => String(item.id) === node.dataset.preset); if (preset) applyPreset(preset); })); }
  function applyPreset(preset) { const config = { ...defaultConfig, ...(preset.config || {}) }; state.config = { ...config, _initialized: true }; state.selectedConcurrency = new Set(config.concurrencies || [1, 2, 3, 4]); $('repetitions-input').value = config.repetitions; $('max-tokens-input').value = config.max_tokens; $('temperature-input').value = config.temperature; $('warmup-input').value = config.warmup; $('seed-input').value = config.seed; $('timeout-input').value = config.timeout; $('prompt-input').value = config.prompt || defaultConfig.prompt; renderConcurrency(); $('preset-list').querySelectorAll('.preset-option').forEach((node) => node.classList.toggle('selected', String(preset.id) === node.dataset.preset)); state.config.preset_id = preset.id; state.config.preset_name = preset.name; updateSelected(); }
  function renderConcurrency() { $('concurrency-chips').innerHTML = [1, 2, 3, 4, 5, 6, 8, 12, 16].map((n) => `<button type="button" class="chip ${state.selectedConcurrency.has(n) ? 'selected' : ''}" data-c="${n}">${n}</button>`).join(''); $('concurrency-chips').querySelectorAll('.chip').forEach((node) => node.addEventListener('click', () => { const n = Number(node.dataset.c); state.selectedConcurrency.has(n) ? state.selectedConcurrency.delete(n) : state.selectedConcurrency.add(n); renderConcurrency(); updateSelected(); })); }

  function renderRecent() { const job = state.jobs.find((x) => x.status === 'completed'); if (!job) return; const completeRuns = (job.runs || []).filter((x) => x.status === 'completed'); const fastest = completeRuns.flatMap((run) => run.summary?.points || []).sort((a, b) => Number(b.aggregate_decode_tps || 0) - Number(a.aggregate_decode_tps || 0))[0]; $('recent-result').className = 'recent-result'; $('recent-result').innerHTML = `<div class="history-card"><div><h4>${esc((job.config?.preset_name || '测试'))}</h4><div class="date">${date(job.finished_at)} · ${completeRuns.length} 个模型</div></div><div class="history-models">${completeRuns.slice(0, 3).map((run) => `<span>${esc(run.model_label)}</span>`).join(' · ')}</div><div class="history-metrics"><div class="history-metric"><strong>${fmt(fastest?.aggregate_decode_tps)}</strong><small>峰值 tok/s</small></div><div class="history-metric"><strong>${fastest?.concurrency || '—'}</strong><small>峰值并发</small></div></div><div class="history-actions"><button class="subtle-button" data-report="${job.id}">打开报告 →</button></div></div>`; $('recent-result').querySelector('[data-report]').addEventListener('click', () => showReport(job.id)); }
  function renderHistory() { const filter = ($('history-filter')?.value || '').toLowerCase(); const status = $('history-status')?.value || ''; const jobs = state.jobs.filter((job) => (!status || job.status === status) && (!filter || JSON.stringify(job.config || {}).toLowerCase().includes(filter) || (job.runs || []).some((run) => `${run.model_id} ${run.model_label}`.toLowerCase().includes(filter)))); const box = $('history-list'); if (!jobs.length) { box.innerHTML = '<div class="empty-block">还没有符合条件的历史记录。</div>'; return; } box.innerHTML = jobs.map((job) => { const runs = job.runs || []; const points = runs.flatMap((run) => run.summary?.points || []); const peak = points.sort((a, b) => Number(b.aggregate_decode_tps || 0) - Number(a.aggregate_decode_tps || 0))[0]; const chosen = state.compare.includes(job.id); return `<article class="history-card"><div><h4>${esc(job.config?.preset_name || '自定义测试')}</h4><div class="date">${date(job.created_at)} · ${esc(job.status)}</div></div><div class="history-models">${runs.length ? runs.map((run) => `<span>${esc(run.model_label)}</span>`).join(' · ') : '<span>尚未产生模型结果</span>'}</div><div class="history-metrics"><div class="history-metric"><strong>${fmt(peak?.aggregate_decode_tps)}</strong><small>峰值 tok/s</small></div><div class="history-metric"><strong>${peak?.concurrency || '—'}</strong><small>并发</small></div></div><div class="history-actions"><button class="subtle-button" data-report="${job.id}">报告</button><button class="subtle-button" data-compare="${job.id}">${chosen ? '已加入' : '加入对比'}</button></div></article>`; }).join(''); box.querySelectorAll('[data-report]').forEach((button) => button.addEventListener('click', () => showReport(button.dataset.report))); box.querySelectorAll('[data-compare]').forEach((button) => button.addEventListener('click', () => toggleCompare(button.dataset.compare))); }
  async function toggleCompare(id) { if (state.compare.includes(id)) state.compare = state.compare.filter((x) => x !== id); else if (state.compare.length < 4) state.compare.push(id); else return toast('最多同时对比 4 条记录', 'error'); renderHistory(); await renderCompare(); }

  function navigate(view) { document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.view === view)); document.querySelectorAll('.view').forEach((node) => node.classList.toggle('active-view', node.id === `view-${view}`)); const labels = { run: ['RUN / CONFIGURE', '新建一次测试'], history: ['RUN ARCHIVE', '历史记录'], compare: ['SIDE BY SIDE', '对比测试'], settings: ['LOW FREQUENCY / CONTROL', '设置'] }; $('view-eyebrow').textContent = labels[view][0]; $('view-title').textContent = labels[view][1]; if (view === 'history') { loadHistory(); } if (view === 'compare') renderCompare(); }
  async function renderCompare() { const empty = $('compare-empty'); const content = $('compare-content'); if (!state.compare.length) { empty.classList.remove('hidden'); content.classList.add('hidden'); return; } try { const details = await Promise.all(state.compare.map((id) => api(`/api/jobs/${id}`))); empty.classList.add('hidden'); content.classList.remove('hidden'); const runs = details.flatMap((job) => (job.runs || []).map((run) => ({ ...run, job }))); $('compare-summary').innerHTML = runs.map((run) => `<div class="compare-chip"><strong>${esc(run.model_label)}</strong><span>${date(run.job.created_at)} · ${esc(run.job.config?.preset_name || '')}</span></div>`).join(''); $('compare-chart').innerHTML = `<div class="chart-title"><h4>聚合 decode 吞吐</h4><span class="chart-legend">tok/s · 并发横轴</span></div>${makeChart(runs.map((run) => ({ label: run.model_label, points: run.summary?.points || [] })))}`; $('compare-table').innerHTML = `<table class="data-table"><thead><tr><th>模型</th><th>甜点并发</th><th>峰值聚合</th><th>单路 c=1</th><th>TTFT p50</th></tr></thead><tbody>${runs.map((run) => { const points = run.summary?.points || []; const peak = points.reduce((a, b) => Number(a?.aggregate_decode_tps || 0) > Number(b?.aggregate_decode_tps || 0) ? a : b, null); return `<tr><td>${esc(run.model_label)}</td><td>${run.summary?.sweet_spot?.concurrency || '—'}</td><td>${fmt(peak?.aggregate_decode_tps)}</td><td>${fmt(points[0]?.avg_stream_decode_tps)}</td><td>${fmt(points[0]?.ttft_p50_s)}s</td></tr>`; }).join('')}</tbody></table>`; } catch (error) { toast(error.message, 'error'); } }
  function makeChart(series) { const width = 900, height = 225, left = 43, right = 12, top = 15, bottom = 30; const all = series.flatMap((item) => item.points); const xs = [...new Set(all.map((point) => Number(point.concurrency)))].sort((a, b) => a - b); const max = Math.max(1, ...all.map((point) => Number(point.aggregate_decode_tps || 0))); const x = (value) => left + (xs.indexOf(Number(value)) / Math.max(1, xs.length - 1)) * (width - left - right); const y = (value) => height - bottom - (Number(value || 0) / max) * (height - top - bottom); const colors = ['#67a9ff', '#5ee1ce', '#ff8f72', '#f8c86b']; const grid = [0, .25, .5, .75, 1].map((ratio) => `<line x1="${left}" y1="${y(max * ratio)}" x2="${width-right}" y2="${y(max * ratio)}" stroke="currentColor" opacity=".12"/><text x="3" y="${y(max*ratio)+3}">${fmt(max*ratio, 0)}</text>`).join(''); const lines = series.map((item, index) => { const points = item.points.map((point) => `${x(point.concurrency)},${y(point.aggregate_decode_tps)}`).join(' '); return `<polyline points="${points}" fill="none" stroke="${colors[index % colors.length]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${item.points.map((point) => `<circle cx="${x(point.concurrency)}" cy="${y(point.aggregate_decode_tps)}" r="4" fill="${colors[index % colors.length]}"/>`).join('')}<text x="${Math.min(width-130, x(item.points[item.points.length-1]?.concurrency || xs[0])+8)}" y="${y(item.points[item.points.length-1]?.aggregate_decode_tps)-7}" fill="${colors[index % colors.length]}">${esc(item.label)}</text>`; }).join(''); const labels = xs.map((value) => `<text x="${x(value)}" y="${height-8}" text-anchor="middle">c=${value}</text>`).join(''); return `<svg class="chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="吞吐曲线">${grid}${lines}${labels}</svg>`; }

  async function startRun() { const endpoint = state.endpoints.find((item) => item.id === state.activeEndpointId); const selected = state.models.filter((model) => state.selectedModels.has(model.id)).map((model) => ({ id: model.id, label: model.id })); if (!endpoint || !selected.length) return; const benchmark = { ...defaultConfig, ...state.config, concurrencies: [...state.selectedConcurrency].sort((a, b) => a - b), repetitions: Number($('repetitions-input').value), max_tokens: Number($('max-tokens-input').value), temperature: Number($('temperature-input').value), warmup: Number($('warmup-input').value), timeout: Number($('timeout-input').value), seed: Number($('seed-input').value), prompt: $('prompt-input').value }; try { const result = await api('/api/jobs', { method: 'POST', body: JSON.stringify({ endpoint_id: endpoint.id, models: selected, preset_id: state.config.preset_id, preset_name: state.config.preset_name || '自定义', benchmark }) }); openDrawer(result.id, selected); } catch (error) { toast(error.message, 'error'); } }
  function openDrawer(jobId, models) { $('run-drawer').classList.remove('hidden'); $('cancel-run-btn').dataset.job = jobId; $('drawer-history-btn').classList.add('hidden'); $('progress-bar').style.width = '3%'; $('progress-label').textContent = '已加入队列，等待执行…'; $('progress-models').innerHTML = models.map((model) => `<div class="progress-model" data-progress-model="${esc(model.id)}"><span class="status-dot"></span><div><strong>${esc(model.label)}</strong><small>queued</small></div></div>`).join(''); if (state.eventSource) state.eventSource.close(); const source = new EventSource(`/api/events/${jobId}/stream`); state.eventSource = source; const handle = (event) => { let data = {}; try { data = JSON.parse(event.data); } catch (_) {} updateProgress(data, event.type); }; ['snapshot', 'queued', 'model_start', 'phase', 'batch_result', 'model_done', 'model_error', 'job_status', 'error'].forEach((type) => source.addEventListener(type, handle)); source.onerror = () => { if (!['completed', 'failed', 'cancelled'].includes($('run-drawer').dataset.status)) pollJob(jobId); }; }
  async function pollJob(jobId) { for (let i = 0; i < 80; i += 1) { await new Promise((resolve) => setTimeout(resolve, 3000)); try { const job = await api(`/api/jobs/${jobId}`); updateProgress({ status: job.status, progress: job.progress }, 'snapshot'); if (['completed', 'failed', 'cancelled', 'interrupted'].includes(job.status)) { finishDrawer(job); return; } } catch (_) { return; } } }
  function updateProgress(data, type) { const status = data.status || data.progress?.status; if (status) $('run-drawer').dataset.status = status; if (type === 'model_start') { $('drawer-title').textContent = `正在测试 ${data.model_label}`; const node = document.querySelector(`[data-progress-model="${CSS.escape(data.model_id)}"]`); if (node) { node.querySelector('.status-dot').className = 'status-dot warn'; node.querySelector('small').textContent = 'running'; } } if (type === 'phase') { const name = data.name || ''; const label = { preload: '预加载模型（不计入测速）', preload_ready: '模型已就绪', warmup: '预热请求', benchmark: `并发 c=${data.concurrency} · 第 ${data.repetition} 次`, snapshot: '保存运行参数' }[name] || name; $('progress-label').textContent = label; const done = Number(data.completed_batches || 0), total = Number(data.total_batches || 1); $('progress-bar').style.width = `${Math.max(4, Math.min(96, done / total * 100))}%`; } if (type === 'batch_result') { const done = Number(data.completed_batches || 0); $('progress-runtime').textContent = `c=${data.concurrency} · ${fmt(data.aggregate_decode_tps)} tok/s`; } if (type === 'model_done') { const node = document.querySelector(`[data-progress-model="${CSS.escape(data.model_id)}"]`); if (node) { node.querySelector('.status-dot').className = 'status-dot ok'; node.querySelector('small').textContent = 'complete'; } } if (type === 'model_error') toast(`${data.model_id}：${data.error}`, 'error'); if (type === 'job_status' && ['completed', 'failed', 'cancelled', 'interrupted'].includes(data.status)) { $('run-drawer').dataset.status = data.status; setTimeout(async () => { const job = await api(`/api/jobs/${$('cancel-run-btn').dataset.job}`); finishDrawer(job); }, 250); } }
  function finishDrawer(job) { $('drawer-title').textContent = job.status === 'completed' ? '测试完成' : `测试${job.status === 'cancelled' ? '已取消' : '未完整完成'}`; $('progress-label').textContent = job.status === 'completed' ? '所有已选模型均已写入历史。' : (job.error || '已有部分结果保留在历史中。'); $('progress-bar').style.width = job.status === 'completed' ? '100%' : '65%'; $('drawer-history-btn').classList.remove('hidden'); $('drawer-history-btn').onclick = () => { $('run-drawer').classList.add('hidden'); showReport(job.id); }; loadHistory(); if (job.status === 'completed') setTimeout(() => showReport(job.id), 700); }

  async function showReport(jobId) { try { const job = await api(`/api/jobs/${jobId}/share`); state.currentJob = job; $('report-content').innerHTML = reportHtml(job); $('report-modal').classList.remove('hidden'); $('download-png-btn').onclick = () => downloadPng(job); } catch (error) { toast(error.message, 'error'); } }
  function reportHtml(job) { const runs = (job.runs || []).filter((run) => run.status === 'completed'); const points = runs.flatMap((run) => run.summary?.points || []); const peak = points.reduce((a, b) => Number(a?.aggregate_decode_tps || 0) > Number(b?.aggregate_decode_tps || 0) ? a : b, null); const average = runs.length ? runs.reduce((sum, run) => sum + Number(run.summary?.points?.[0]?.avg_stream_decode_tps || 0), 0) / runs.length : null; return `<div class="report-head"><div><p class="eyebrow">BENCHROOM / PERFORMANCE REPORT</p><h3>${esc(job.config?.preset_name || 'Benchmark')}</h3><p>${date(job.created_at)} · ${esc(job.config?.base_url || 'local endpoint')} · ${runs.length} models</p></div><span class="report-flag">● REDACTED SHARE VIEW</span></div><div class="report-insights"><div class="report-insight"><strong>${fmt(peak?.aggregate_decode_tps)}</strong><span>峰值聚合 decode · tok/s</span></div><div class="report-insight"><strong>${peak?.concurrency || '—'}</strong><span>峰值并发</span></div><div class="report-insight"><strong>${fmt(average)}</strong><span>模型平均单路速度 · tok/s</span></div></div><div class="chart-panel"><div class="chart-title"><h4>并发跑道 / Aggregate decode</h4><span class="chart-legend">${esc(job.config?.benchmark?.max_tokens || '—')} output tokens</span></div>${makeChart(runs.map((run) => ({ label: run.model_label, points: run.summary?.points || [] })))}</div>${runs.map((run) => { const p = run.summary?.points || []; const evidence = run.runtime_snapshot || {}; const lm = evidence.lemonade_model || {}; const props = evidence.llama_props || {}; const params = props.default_generation_settings || {}; const ctx = params.n_ctx || lm.recipe_options?.ctx_size || '—'; const recipe = lm.recipe ? `${lm.recipe}${lm.device ? ` · ${lm.device}` : ''}` : '未取到 Lemonade 运行信息'; const build = props.build_info || 'build 未返回'; const match = evidence.model_match?.mode || 'unknown'; return `<div class="report-model-block"><h4>${esc(run.model_label)}</h4><p class="report-sub">甜点并发 c=${run.summary?.sweet_spot?.concurrency || '—'} · ${run.summary?.sweet_spot?.reason || '—'}</p><p class="report-sub">运行证据：ctx ${esc(ctx)} · ${esc(recipe)} · ${esc(build)} · model match ${esc(match)}</p><table><thead><tr><th>并发</th><th>聚合 decode</th><th>每路 stream</th><th>TTFT p50</th><th>失败</th></tr></thead><tbody>${p.map((point) => `<tr><td>c=${point.concurrency}</td><td>${fmt(point.aggregate_decode_tps)}</td><td>${fmt(point.avg_stream_decode_tps)}</td><td>${fmt(point.ttft_p50_s)}s</td><td>${point.failed_requests || 0}</td></tr>`).join('')}</tbody></table></div>`; }).join('')}<p class="report-foot">分享视图已隐藏提示词、主机身份、绝对路径和秘密。完整证据只保存在本机历史数据库。</p>`; }
  function downloadPng(job) { const runs = (job.runs || []).filter((run) => run.status === 'completed'); const canvas = document.createElement('canvas'); canvas.width = 1800; canvas.height = 1200 + runs.length * 230; const ctx = canvas.getContext('2d'); ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--paper-2').trim() || '#151f29'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--ink').trim() || '#e8edf4'; ctx.font = '800 42px Manrope, sans-serif'; ctx.fillText(job.config?.preset_name || 'Benchmark', 85, 105); ctx.fillStyle = '#67a9ff'; ctx.font = '500 18px monospace'; ctx.fillText('BENCHROOM / PERFORMANCE REPORT · REDACTED SHARE VIEW', 85, 57); ctx.fillStyle = '#8a98a9'; ctx.font = '18px monospace'; ctx.fillText(`${date(job.created_at)} · ${runs.length} models`, 85, 145); const all = runs.flatMap((run) => run.summary?.points || []); const max = Math.max(1, ...all.map((x) => Number(x.aggregate_decode_tps || 0))); const chartX = 85, chartY = 205, chartW = 1630, chartH = 350; ctx.strokeStyle = 'rgba(171,194,220,.18)'; ctx.lineWidth = 1; for (let i = 0; i < 5; i += 1) { const yy = chartY + chartH - i * chartH / 4; ctx.beginPath(); ctx.moveTo(chartX, yy); ctx.lineTo(chartX + chartW, yy); ctx.stroke(); } const colors = ['#67a9ff', '#5ee1ce', '#ff8f72', '#f8c86b']; runs.forEach((run, index) => { const pts = run.summary?.points || []; ctx.strokeStyle = colors[index % colors.length]; ctx.lineWidth = 5; ctx.beginPath(); pts.forEach((point, pointIndex) => { const xx = chartX + (pointIndex / Math.max(1, pts.length - 1)) * chartW; const yy = chartY + chartH - Number(point.aggregate_decode_tps || 0) / max * chartH; pointIndex ? ctx.lineTo(xx, yy) : ctx.moveTo(xx, yy); }); ctx.stroke(); ctx.fillStyle = colors[index % colors.length]; ctx.font = '18px monospace'; ctx.fillText(run.model_label, chartX + chartW - 280, chartY + 30 + index * 27); }); runs.forEach((run, index) => { const y = 625 + index * 220; ctx.fillStyle = '#e8edf4'; ctx.font = '700 24px Manrope, sans-serif'; ctx.fillText(run.model_label, 85, y); ctx.fillStyle = '#8a98a9'; ctx.font = '17px monospace'; const p = run.summary?.points || []; ctx.fillText(`sweet spot c=${run.summary?.sweet_spot?.concurrency || '—'}   ` + p.map((x) => `c${x.concurrency} ${fmt(x.aggregate_decode_tps)} tok/s`).join('   '), 85, y + 39); ctx.strokeStyle = 'rgba(171,194,220,.2)'; ctx.beginPath(); ctx.moveTo(85, y + 64); ctx.lineTo(1715, y + 64); ctx.stroke(); }); const link = document.createElement('a'); link.download = `benchroom-${new Date().toISOString().slice(0, 10)}.png`; link.href = canvas.toDataURL('image/png'); link.click(); }

  function renderEndpoints() { $('endpoint-select').innerHTML = state.endpoints.map((endpoint) => `<option value="${endpoint.id}">${esc(endpoint.name)}</option>`).join(''); if (state.activeEndpointId) $('endpoint-select').value = String(state.activeEndpointId); $('endpoint-list').innerHTML = state.endpoints.map((endpoint) => `<div class="endpoint-item ${endpoint.id === state.activeEndpointId ? 'active' : ''}"><span class="endpoint-icon">↗</span><div><strong>${esc(endpoint.name)}</strong><small>${esc(endpoint.base_url)} · ${esc(endpoint.kind)}</small></div><button class="subtle-button" data-edit-endpoint="${endpoint.id}">编辑</button></div>`).join(''); $('endpoint-list').querySelectorAll('[data-edit-endpoint]').forEach((button) => button.addEventListener('click', () => editEndpoint(Number(button.dataset.editEndpoint)))); }
  function editEndpoint(id) { const endpoint = state.endpoints.find((item) => item.id === id); if (!endpoint) return; $('endpoint-form').classList.remove('hidden'); $('endpoint-id').value = endpoint.id; $('endpoint-name').value = endpoint.name; $('endpoint-base').value = endpoint.base_url; $('endpoint-kind').value = endpoint.kind; $('endpoint-lemonade').value = endpoint.lemonade_url || ''; $('endpoint-key-env').value = endpoint.api_key_env || ''; }
  function newEndpoint() { $('endpoint-form').classList.remove('hidden'); $('endpoint-id').value = ''; ['endpoint-name', 'endpoint-base', 'endpoint-lemonade', 'endpoint-key-env'].forEach((id) => $(id).value = ''); $('endpoint-kind').value = 'auto'; }
  async function saveEndpoint(event) { event.preventDefault(); try { await api('/api/endpoints', { method: 'POST', body: JSON.stringify({ id: $('endpoint-id').value || null, name: $('endpoint-name').value, base_url: $('endpoint-base').value, kind: $('endpoint-kind').value, lemonade_url: $('endpoint-lemonade').value || null, api_key_env: $('endpoint-key-env').value || null }) }); $('endpoint-form').classList.add('hidden'); await loadEndpoints(); await loadModels(); toast('端点已保存'); } catch (error) { toast(error.message, 'error'); } }
  async function savePreset() { const name = window.prompt('预设名称'); if (!name) return; try { await api('/api/presets', { method: 'POST', body: JSON.stringify({ name, description: '从当前测试配置保存', config: readConfig() }) }); await loadPresets(); toast('预设已保存'); } catch (error) { toast(error.message, 'error'); } }
  function readConfig() { return { concurrencies: [...state.selectedConcurrency].sort((a, b) => a - b), repetitions: Number($('repetitions-input').value), max_tokens: Number($('max-tokens-input').value), temperature: Number($('temperature-input').value), warmup: Number($('warmup-input').value), timeout: Number($('timeout-input').value), seed: Number($('seed-input').value), prompt: $('prompt-input').value, preload: true, unique_prompts: true }; }

  $('auth-form').addEventListener('submit', async (event) => { event.preventDefault(); const password = $('password-input').value; if ($('auth-shell').dataset.setup === '1' && password !== $('password-confirm').value) return toast('两次密码不一致', 'error'); try { const result = await api($('auth-shell').dataset.setup === '1' ? '/api/setup' : '/api/login', { method: 'POST', body: JSON.stringify({ password }) }); state.csrf = result.csrf; $('password-input').value = ''; showApp(); await loadWorkspace(); } catch (error) { toast(error.message, 'error'); } });
  $('logout-btn').addEventListener('click', async () => { try { await api('/api/logout', { method: 'POST', body: '{}' }); } finally { showAuth(false); } });
  document.querySelectorAll('[data-view], [data-view-link]').forEach((node) => node.addEventListener('click', () => navigate(node.dataset.view || node.dataset.viewLink)));
  $('refresh-models').addEventListener('click', () => loadModels()); $('refresh-history').addEventListener('click', () => loadHistory()); $('history-filter').addEventListener('input', () => renderHistory()); $('history-status').addEventListener('change', () => renderHistory()); $('start-run-btn').addEventListener('click', startRun); $('save-preset-btn').addEventListener('click', savePreset); $('new-endpoint-btn').addEventListener('click', newEndpoint); $('cancel-endpoint-btn').addEventListener('click', () => $('endpoint-form').classList.add('hidden')); $('endpoint-form').addEventListener('submit', saveEndpoint); $('cancel-run-btn').addEventListener('click', async () => { try { await api(`/api/jobs/${$('cancel-run-btn').dataset.job}/cancel`, { method: 'POST', body: '{}' }); toast('已请求取消，正在收尾…'); } catch (error) { toast(error.message, 'error'); } }); $('close-report-btn').addEventListener('click', () => $('report-modal').classList.add('hidden')); $('theme-btn').addEventListener('click', () => { state.theme = state.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('bench-theme', state.theme); applyTheme(); });
  $('endpoint-select').addEventListener('change', () => { state.activeEndpointId = Number($('endpoint-select').value); state.selectedModels.clear(); const endpoint = state.endpoints.find((item) => item.id === state.activeEndpointId); if (endpoint) updateEndpointLabel(endpoint); renderEndpoints(); loadModels(); loadHealth(); });
  document.addEventListener('keydown', (event) => { if ((event.metaKey || event.ctrlKey) && ['1', '2', '3', '4'].includes(event.key)) { event.preventDefault(); navigate(['run', 'history', 'compare', 'settings'][Number(event.key) - 1]); } if (event.key === 'Escape') { $('report-modal').classList.add('hidden'); } });
  renderConcurrency(); boot();
})();
